routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   return view('welcome');
});

// Route::get('/welcome', function () {
//     return view('welcome');
// });




Route::resource('post', 'PostController');

Route::get('/profil', function () {
    return view('profil.profil');
});

Route::get('/profil/edit', function () {
    return view('profil.updateprofil');
});

Route::get('/komentar', function () {
    return view('komentar/komentar');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Foto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Foto extends Model
{
    protected $table = "foto";
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $table = "postingan";
    protected $fillable = ["isi_postingan", "user_id"];


    function upfoto(){
    	return $this->hasMany('App\Foto');
    }

    public function author(){
    	return $this->belongsTo('App\User','user_id');
    }
}

app/Profil.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profil extends Model
{
    protected $table = "profil";
    protected $fillable = [
        'nama_lengkap', 'jenis_kelamin'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = "user";
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/KomentarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;

class KomentarController extends Controller
{
    public function create (){
        return view('komentar.create');
    }

    public function store(Request $request){
        dd($request->all());
        $query = DB::table('komentar')->insert([
        "isi_komentar" => $request["isi_komentar"],
       /* "postingan_id" => 1,
        "user_id" => 1*/
        ]);
        return redirect('komentar/create');
    }

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Post;
use Auth;

class PostController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $postingan = DB::table('postingan')->join('user', 'user_id', '=', 'user.id')
        ->select(
            'postingan.id',
            'postingan.isi_postingan',
            'postingan.created_at',
            'postingan.updated_at',
            'postingan.user_id',
            'user.name'
        )
        ->get();

        // $postingan = Post::all();

        return view('post.feeds', compact('postingan'));    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('post.posting');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'isi_postingan' => 'required'
            // 'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048'
        ]);

        //build
        // $query = DB::table('postingan')->insert([
        //     "isi_postingan" => $request["isi_postingan"]
        // ]);

        //ORM
        // $pertanyaan = new Pertanyaan;
        // $pertanyaan->judul = $request['judul'];
        // $pertanyaan->isi = $request['isi'];
        // $pertanyaan->save();

        $post = Post::create([
            
            "isi_postingan" => $request["isi_postingan"],
            "user_id" => Auth::id()
        ]);
        return redirect('/post')->with('success','Postingan Berhasil Ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $postingan = Post::find($id);

        return view('komentar.komentar', compact('postingan'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $postingan = Post::find($id);        
        return view('post.edit_post', compact('postingan'));
        //return view('post.edit_post');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $update = Post::where("id", $id) -> update ([
            "isi_postingan" => $request ["isi_postingan"]
        ]);


        return redirect('/post')->with('success','Postingan Berhasil Diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Post::destroy($id);
        return redirect('/post')->with('success','Postingan Berhasil Dihapus');
    }
}

app/Http/Controllers/ProfilController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ProfilController extends Controller
{
    //
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>

                <div class="card-body">
                <a href="/post/">
                        <svg class="olymp-newsfeed-icon left-menu-icon" data-toggle="tooltip" data-placement="right"   data-original-title="NEWSFEED"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-newsfeed-icon')}}"></use></svg>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/komentar/create.blade.php
@extends('main.master')

@section('content')

<div id="newsfeed-items-grid">

				<div class="ui-block">

					
					<article class="hentry post">
					
						<div class="post__author author vcard inline-items">
							<img src="{{ asset('/olympus-html/img/avatar10-sm.jpg')}}" alt="author">
					
							<div class="author-date">
								<a class="h6 post__author-name fn" href="#">Elaine Dreyfuss</a>
								<div class="post__date">
									<time class="published" datetime="2004-07-24T18:18">
										9 hours ago
									</time>
								</div>
							</div>
					
							<div class="more"><svg class="olymp-three-dots-icon"><use xlink:href="svg-icons/sprites/icons.svg#olymp-three-dots-icon"></use></svg>
								<ul class="more-dropdown">
									<li>
										<a href="#">Edit Post</a>
									</li>
									<li>
										<a href="#">Delete Post</a>
									</li>
									<li>
										<a href="#">Turn Off Notifications</a>
									</li>
									<li>
										<a href="#">Select as Featured</a>
									</li>
								</ul>
							</div>
					
						</div>
					
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempo incididunt ut
							labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris consequat.
						</p>
					
						<div class="post-additional-info inline-items">
					
							<a href="#" class="post-add-icon inline-items">
								<svg class="olymp-heart-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-heart-icon')}}"></use></svg>
								<span>24</span>
							</a>
					
							<ul class="friends-harmonic">
								<li>
									<a href="#">
										<img src="{{ asset('/olympus-html/img/friend-harmonic7.jpg')}}" alt="friend">
									</a>
								</li>
								<li>
									<a href="#">
										<img src="{{ asset('/olympus-html/img/friend-harmonic8.jpg')}}" alt="friend">
									</a>
								</li>
								<li>
									<a href="#">
										<img src="{{ asset('/olympus-html/img/friend-harmonic9.jpg')}}" alt="friend">
									</a>
								</li>
								<li>
									<a href="#">
										<img src="img/friend-harmonic10.jpg" alt="friend">
									</a>
								</li>
								<li>
									<a href="#">
										<img src="{{ asset('/olympus-html/img/friend-harmonic11.jpg')}}" alt="friend">
									</a>
								</li>
							</ul>
					
							<div class="names-people-likes">
								<a href="#">You</a>, <a href="#">Elaine</a> and
								<br>22 more liked this
							</div>
					
					
							<div class="comments-shared">
								<a href="#" class="post-add-icon inline-items">
									<svg class="olymp-speech-balloon-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-speech-balloon-icon')}}"></use></svg>
									<span>17</span>
								</a>
					
								
							</div>
					
					
						</div>
					
						<div class="control-block-button post-control-button">
					
							<a href="#" class="btn btn-control">
								<svg class="olymp-like-post-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-like-post-icon')}}"></use></svg>
							</a>
					
							<a href="#" class="btn btn-control">
								<svg class="olymp-comments-post-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-comments-post-icon')}}"></use></svg>
							</a>
					
							
					
						</div>
					
					</article>
					
					<!-- Comments -->
					
					<ul class="comments-list">
						<li class="comment-item">
							<div class="post__author author vcard inline-items">
								<img src="img/author-page.jpg" alt="author">
					
								<div class="author-date">
									<a class="h6 post__author-name fn" href="{{ asset('/olympus-html/02-ProfilePage.html')}}">James Spiegel</a>
									<div class="post__date">
										<time class="published" datetime="2004-07-24T18:18">
											38 mins ago
										</time>
									</div>
								</div>
					
								<a href="#" class="more"><svg class="olymp-three-dots-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-three-dots-icon')}}"></use></svg></a>
					
							</div>
					
							<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium der doloremque laudantium.</p>
					
							<a href="#" class="post-add-icon inline-items">
								<svg class="olymp-heart-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-heart-icon')}}"></use></svg>
								<span>3</span>
							</a>
													</li>
						<li class="comment-item">
							<div class="post__author author vcard inline-items">
								<img src="{{ asset('/olympus-html/img/avatar1-sm.jpg')}}" alt="author">
					
								<div class="author-date">
									<a class="h6 post__author-name fn" href="#">Mathilda Brinker</a>
									<div class="post__date">
										<time class="published" datetime="2004-07-24T18:18">
											1 hour ago
										</time>
									</div>
								</div>
					
								<a href="#" class="more"><svg class="olymp-three-dots-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-three-dots-icon')}}"></use></svg></a>
					
							</div>
					
							<p>Ratione voluptatem sequi en lod nesciunt. Neque porro quisquam est, quinder dolorem ipsum
								quia dolor sit amet, consectetur adipisci velit en lorem ipsum duis aute irure dolor in reprehenderit in voluptate velit esse cillum.
							</p>
					
							<a href="#" class="post-add-icon inline-items">
								<svg class="olymp-heart-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-heart-icon')}}"></use></svg>
								<span>8</span>
							</a>
							
						</li>
					</ul>
					
					<!-- ... end Comments -->

					<a href="#" class="more-comments">View more comments <span>+</span></a>

					
					<!-- Comment Form  -->
					
					<form class="comment-form inline-items" action="/komentar" method="POST">
					@csrf
					
						<div class="post__author author vcard inline-items">
							<img src="{{ asset('/olympus-html/img/author-page.jpg')}}" alt="author">
					
							<div class="form-group with-icon-right ">
								<textarea class="form-control" id="isi_komentar" name="isi_komentar" placeholder=""></textarea>
			
							</div>
						</div>
					
						<button class="btn btn-md-2 btn-primary">Post Comment</button>
					
						<button class="btn btn-md-2 btn-border-think c-grey btn-transparent custom-color">Cancel</button>
					
					</form>
					
					<!-- ... end Comment Form  -->
				</div>



			</div>

@endsection

resources/views/komentar/komentar.blade.php
@extends('main.master')

@section('content')

<div id="newsfeed-items-grid">

				<div class="ui-block">

					
					<article class="hentry post">
					
						<div class="post__author author vcard inline-items">
							<img src="{{ asset('/olympus-html/img/avatar10-sm.jpg')}}" alt="author">
					
							<div class="author-date">
								<a class="h6 post__author-name fn" href="#">Elaine Dreyfuss</a>
								<div class="post__date">
									<time class="published" datetime="2004-07-24T18:18">
										9 hours ago
									</time>
								</div>
							</div>
					
							<div class="more"><svg class="olymp-three-dots-icon"><use xlink:href="svg-icons/sprites/icons.svg#olymp-three-dots-icon"></use></svg>
								<ul class="more-dropdown">
									<li>
										<a href="#">Edit Post</a>
									</li>
									<li>
										<a href="#">Delete Post</a>
									</li>
									<li>
										<a href="#">Turn Off Notifications</a>
									</li>
									<li>
										<a href="#">Select as Featured</a>
									</li>
								</ul>
							</div>
					
						</div>
					
						<p>
							{{$postingan->isi_postingan}} 
						</p>
					
						<div class="post-additional-info inline-items">
					
							<a href="#" class="post-add-icon inline-items">
								<svg class="olymp-heart-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-heart-icon')}}"></use></svg>
								<span>24</span>
							</a>
					
							<ul class="friends-harmonic">
								<li>
									<a href="#">
										<img src="{{ asset('/olympus-html/img/friend-harmonic7.jpg')}}" alt="friend">
									</a>
								</li>
								<li>
									<a href="#">
										<img src="{{ asset('/olympus-html/img/friend-harmonic8.jpg')}}" alt="friend">
									</a>
								</li>
								<li>
									<a href="#">
										<img src="{{ asset('/olympus-html/img/friend-harmonic9.jpg')}}" alt="friend">
									</a>
								</li>
								<li>
									<a href="#">
										<img src="img/friend-harmonic10.jpg" alt="friend">
									</a>
								</li>
								<li>
									<a href="#">
										<img src="{{ asset('/olympus-html/img/friend-harmonic11.jpg')}}" alt="friend">
									</a>
								</li>
							</ul>
					
							<div class="names-people-likes">
								<a href="#">You</a>, <a href="#">Elaine</a> and
								<br>22 more liked this
							</div>
					
					
							<div class="comments-shared">
								<a href="#" class="post-add-icon inline-items">
									<svg class="olymp-speech-balloon-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-speech-balloon-icon')}}"></use></svg>
									<span>17</span>
								</a>
					
								
							</div>
					
					
						</div>
					
						<div class="control-block-button post-control-button">
					
							<a href="#" class="btn btn-control">
								<svg class="olymp-like-post-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-like-post-icon')}}"></use></svg>
							</a>
					
							<a href="#" class="btn btn-control">
								<svg class="olymp-comments-post-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-comments-post-icon')}}"></use></svg>
							</a>
					
							
					
						</div>
					
					</article>
					
					<!-- Comments -->
					
					<ul class="comments-list">
						<li class="comment-item">
							<div class="post__author author vcard inline-items">
								<img src="img/author-page.jpg" alt="author">
					
								<div class="author-date">
									<a class="h6 post__author-name fn" href="{{ asset('/olympus-html/02-ProfilePage.html')}}">James Spiegel</a>
									<div class="post__date">
										<time class="published" datetime="2004-07-24T18:18">
											38 mins ago
										</time>
									</div>
								</div>
					
								<a href="#" class="more"><svg class="olymp-three-dots-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-three-dots-icon')}}"></use></svg></a>
					
							</div>
					
							<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium der doloremque laudantium.</p>
					
							<a href="#" class="post-add-icon inline-items">
								<svg class="olymp-heart-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-heart-icon')}}"></use></svg>
								<span>3</span>
							</a>
													</li>
						<li class="comment-item">
							<div class="post__author author vcard inline-items">
								<img src="{{ asset('/olympus-html/img/avatar1-sm.jpg')}}" alt="author">
					
								<div class="author-date">
									<a class="h6 post__author-name fn" href="#">Mathilda Brinker</a>
									<div class="post__date">
										<time class="published" datetime="2004-07-24T18:18">
											1 hour ago
										</time>
									</div>
								</div>
					
								<a href="#" class="more"><svg class="olymp-three-dots-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-three-dots-icon')}}"></use></svg></a>
					
							</div>
					
							<p>Ratione voluptatem sequi en lod nesciunt. Neque porro quisquam est, quinder dolorem ipsum
								quia dolor sit amet, consectetur adipisci velit en lorem ipsum duis aute irure dolor in reprehenderit in voluptate velit esse cillum.
							</p>
					
							<a href="#" class="post-add-icon inline-items">
								<svg class="olymp-heart-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-heart-icon')}}"></use></svg>
								<span>8</span>
							</a>
							
						</li>
					</ul>
					
					<!-- ... end Comments -->

					<a href="#" class="more-comments">View more comments <span>+</span></a>

					
					<!-- Comment Form  -->
					
					<form class="comment-form inline-items">
					
						<div class="post__author author vcard inline-items">
							<img src="{{ asset('/olympus-html/img/author-page.jpg')}}" alt="author">
					
							<div class="form-group with-icon-right ">
								<textarea class="form-control" placeholder=""></textarea>
			
							</div>
						</div>
					
						<button class="btn btn-md-2 btn-primary">Post Comment</button>
					
						<button class="btn btn-md-2 btn-border-think c-grey btn-transparent custom-color">Cancel</button>
					
					</form>
					
					<!-- ... end Comment Form  -->
				</div>



			</div>

@endsection

resources/views/post/feeds.blade.php
@extends('main.master')

@section('content')



<div id="newsfeed-items-grid">
	


				<div class="ui-block">

					
					<article class="hentry post">
					
						<div class="post__author author vcard inline-items">
							<img src="{{ asset('/olympus-html/img/avatar10-sm.jpg')}}" alt="author">
					
							<div class="author-date">
								<a class="h6 post__author-name fn" href="#">Elaine Dreyfuss</a>
								<div class="post__date">
									<time class="published" datetime="2004-07-24T18:18">
										9 hours ago
									</time>
								</div>
							</div>
					
							<div class="more"><svg class="olymp-three-dots-icon"><use xlink:href="svg-icons/sprites/icons.svg#olymp-three-dots-icon"></use></svg>
								<ul class="more-dropdown">
									<li>
										<a href="#">Edit Post</a>
									</li>
									<li>
										<a href="#">Delete Post</a>
									</li>
									<li>
										<a href="#">Turn Off Notifications</a>
									</li>
									<li>
										<a href="#">Select as Featured</a>
									</li>
								</ul>
							</div>
					
						</div>
					
                  	
                      <p>
                      	
                      </p>
                       
                      
                      
               
                   
                  	  					
						<div class="post-additional-info inline-items">
					
							<a href="#" class="post-add-icon inline-items">
								<svg class="olymp-heart-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-heart-icon')}}"></use></svg>
								<span>24</span>
							</a>
					
							<ul class="friends-harmonic">
								<li>
									<a href="#">
										<img src="{{ asset('/olympus-html/img/friend-harmonic7.jpg')}}" alt="friend">
									</a>
								</li>
								<li>
									<a href="#">
										<img src="{{ asset('/olympus-html/img/friend-harmonic8.jpg')}}" alt="friend">
									</a>
								</li>
								<li>
									<a href="#">
										<img src="{{ asset('/olympus-html/img/friend-harmonic9.jpg')}}" alt="friend">
									</a>
								</li>
								<li>
									<a href="#">
										<img src="img/friend-harmonic10.jpg" alt="friend">
									</a>
								</li>
								<li>
									<a href="#">
										<img src="{{ asset('/olympus-html/img/friend-harmonic11.jpg')}}" alt="friend">
									</a>
								</li>
							</ul>
					
							<div class="names-people-likes">
								<a href="#">You</a>, <a href="#">Elaine</a> and
								<br>22 more liked this
							</div>
					
					
							<div class="comments-shared">
								<a href="/komentar" class="post-add-icon inline-items">
									<svg class="olymp-speech-balloon-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-speech-balloon-icon')}}"></use></svg>
									<span>17</span>
								</a>
			
								
							</div>
					
					
						</div>
					
						<div class="control-block-button post-control-button">
					
							<a href="#" class="btn btn-control">
								<svg class="olymp-like-post-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-like-post-icon')}}"></use></svg>
							</a>
					
							<a href="#" class="btn btn-control">
								<svg class="olymp-comments-post-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-comments-post-icon')}}"></use></svg>
							</a>
					
							
					
						</div>
					
					</article>
					
					<!-- Comments -->
					

					
					<!-- ... end Comments -->

					
					<!-- Comment Form  -->
			


			</div>




<div class="card">
             <div class="card-header">
                <h3 class="card-title">Postingan Table</h3>
              </div>
              
              <!-- /.card-header -->
              <div class="card-body">
              	@if(session('success'))
              		<div class="alert alert-success">
              			{{ session('success')}}
              		</div>
              	@endif
              	<a class="btn btn-primary" href="{{route('post.create')}}">Buat Postingan baru</a>
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th style="width: 10px">#</th>
                      <th>User</th>
                      <th>Isi</th>
                      <th>Waktu</th>
                      <th style="width: 200px">Action </th>
                    </tr>
                  </thead>
                  <tbody>
                  	@forelse($postingan as $key => $postingan)
                  	<tr>
                      <td> {{ $key +1 }}</td>
                      <td> {{ $postingan->name }}</td>

                      <td> {{ $postingan->isi_postingan }}
                      </td>
                      <td> {{ $postingan->created_at }}</td>
                      <td style="display: flex;"> 
                      	<div class="post-control-button">
					
							<div class="post-additional-info inline-items">
					
							<a href="#" class="post-add-icon inline-items">
								<svg class="olymp-heart-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-heart-icon')}}"></use></svg>
								<span>24</span>
							</a>
		
								<a href="post/{{$postingan->id}}" class="post-add-icon inline-items">
									<svg class="olymp-speech-balloon-icon"><use xlink:href="{{ asset('/olympus-html/svg-icons/sprites/icons.svg#olymp-speech-balloon-icon')}}"></use></svg>
									<span>17</span>
								</a>
								@if ($postingan->user_id == Auth::id())
								<a href="/post/{{$postingan->id}}/edit" class="btn btn-primary btn-sm">edit</a>
								@endif

								@if ($postingan->user_id == Auth::id())
								<form action="post/{{$postingan->id}}" method="POST">
                      		@csrf
                      		@method('DELETE')
                      		<input type="submit" value="delete" class="btn btn-danger btn-sm">
                      		@endif
                      	</form>
	
					
					
						</div>
					
							
					
						</div>
                      </td>
                    </tr>
                    @empty
                    <tr>
                    	<td colspan="4" align="center">No Data</td>
                    </tr>
                  	@endforelse                    
                  </tbody>
                </table>
              </div>
</div>





@endsection